# Workflow mostly copied from https://github.com/actions/hello-world-javascript-action
name: hello world with parameters
on:
  workflow_dispatch:
    inputs:
      who-to-greet:
        description: Who to greet in the log
        required: true
        default: 'World'
        type: string

jobs:
  say-hello:
    name: Say Hello
    runs-on: ubuntu-latest
    steps:
      - name: my-step
        run: echo "Hello ${{ inputs.who-to-greet }} !"
